# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorimeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Raspberry Pi Serial')),
                ('access_code', models.CharField(max_length=100, verbose_name='Access Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('last_comm_time', models.DateTimeField(verbose_name='Time of Last Communication From Device')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nickname')),
                ('target_temp', models.FloatField(verbose_name='Target Temperature (Celsius)')),
                ('ramp_rate', models.FloatField(verbose_name='Rate of Temp Ramp (Celsius per second)')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('is_running', models.BooleanField(default=False, verbose_name='Is currently running?')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Has finished running?')),
            ],
        ),
    ]
