# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='calorimeter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controls.Calorimeter', verbose_name='Calorimeter'),
            preserve_default=False,
        ),
    ]
